# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa92c28a873e06a9151f749c831b89d15f72a1f3839c74df7ee7fb21506ec4354c735a9c261af1214931161fd6fd9be6e660a41b3a363cc3c335c0eb9b23b110

test:
  secret_key_base: bee871512748b4d361c2ee946a9cdec5bff814e5969f9060dc98f9ffb3bc8679f28a512da07bb10c4e7b88a6a66f75f2ddeded531f919e28214881aadb1a4f2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
